# Generated by Django 3.2.5 on 2022-02-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='milelage',
            new_name='mileage',
        ),
    ]
